name: gpt-sovits
services:
  proxy:
    image: "tinyproxy"
    networks:
      - external
      - internal
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
  http:
    image: "caddy"
    networks:
      - external
      - internal
    depends_on:
      - app
    ports:
      - "9870:9870"
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
    volumes:
      - ./caddy.gpt-sovits.Caddyfile:/etc/caddy/Caddyfile
  app:
    image: "breakstring/gpt-sovits:latest"
    networks:
      - internal
    shm_size: 16G
    working_dir: /workspace
    volumes:
      - ./data:/workspace/output:z
      - ./gpt-sovits/logs:/workspace/logs:z
      - ./gpt-sovits/SoVITS_weights:/workspace/SoVITS_weights:z
      - ./gpt-sovits/reference:/workspace/reference:z
    environment:
      - is_half=False
      - http_proxy=http://proxy:8118
      - https_proxy=http://proxy:8118
      - no_proxy=localhost,127.0.0.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

networks:
  external:
  internal:
    internal: true
