name: yolo
services:
  yolo:
    container_name: yolo
    image: allape/yolo:ultralytics-8.3.75-amd64
    restart: unless-stopped
    volumes:
      - ./predictor.py:/ultralytics/predictor.py
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

