name: whisper
services:
  app:
    image: "allape/whisper:latest"
    restart: unless-stopped
    environment:
      #- http_proxy=http://host.docker.internal:1080
      #- https_proxy=http://host.docker.internal:1080
      - no_proxy=localhost,127.0.0.1
      - GGML_CUDA=1
      - WHISPER_CORS=1
    ports:
      - "9090:9090"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
